# Selected 21 templates mined by 4-shot validation set
imagenet_templates = [
    "a good photo of a {}.",
    "a photo of a nice {}.",
    "a photo of the nice {}.",
    "a photo of a cool {}.",
    "a photo of the cool {}.",
    "This is a photo of a {}.",
    "a cropped photo of a {}.",
    "a bad photo of a {}.",
    "A photo of that {}.",
    "a photo of a {}, a type of pet.",
    "A picture of that {}.",
    "A picture of an {}.",
    "a photo of a weird {}.",
    "A picture of a {}.",
    "A picture of this {}.",
    "A photo of this {}.",
    "A photo of an {}.",
    "a photo of one {}.",
    "A photo of these {}.",
    "a low resolution photo of a {}.",
    "a photo of a {}.",
]

flowers_templates = [
    "a photo of a {}, a type of flower.",
    "a photo of a nice {}.",
    "a photo of the nice {}.",
    "a bright photo of the {}.",
    "a cropped photo of the {}.",
    "a photo of a cool {}.",
    "a bright photo of a {}.",
    "a cropped photo of a {}.",
    "a photo of some {}.",
    "a close-up photo of a {}.",
    "This is a photo of a {}.",
    "a close-up photo of the {}.",
    "a photo of many {}.",
    "a photo of the small {}.",
    "a photo of this {}.",
    "a bad photo of a {}.",
    "a photo of an {}.",
    "a {} photo.",
    "a good photo of a {}.",
    "a picture of some {}.",
    "a photo of a small {}.",
]

aircraft_templates = [
  "a rendering of a {}.",
  "This is a photo of a {}.",
  "a example of the person {}.",
  "a example of a person {}.",
  "a photo of the {}, a type of aircraft.",
  "a rendering of the {}.",
  "a picture of an {}.",
  "a photo of a {}.",
  "a photo of a small {}.",
  "a low resolution photo of a {}.",
  "itap of my {}.",
  "a photo of my new {}.",
  "a photo of the small {}.",
  "a cartoon {}.",
  "a picture of a {}.",
  "a photo of a large {}.",
  "a rendition of a {}.",
  "a photo of a {}, a type of pet.",
  "a photo of a nice {}.",
  "a photo of an {}.",
  "That is a photo of a {}.",
]


food_templates = [
    "a photo of the {}.",
    "a bad photo of the {}.",
    "a photo of the nice {}.",
    "a bad photo of a {}.",
    "a blurry photo of the {}.",
    "a close-up photo of the {}.",
    "a photo of your {}.",
    "a picture of the {}.",
    "a cropped photo of the {}.",
    "a photo of a nice {}.",
    "This is a photo of a {}.",
    "This is a {} photo.",
    "a rendering of the {}.",
    "a photo of {}, a type of food.",
    "That is a photo of a {}.",
    "a photo of that {}.",
    "a photo of those {}.",
    "a good photo of the {}.",
    "This is a {} picture.",
    "a pixelated photo of the {}.",
    "a photo of my {}.",
]

pets_templates = [
    "a photo of a {}, a type of pet.",
    "itap of my {}.",
    "a picture of my {}.",
    "a photo of my {}.",
    "a photo of my old {}.",
    "a cropped photo of the {}.",
    "a cropped photo of a {}.",
    "a bad photo of a {}.",
    "a photo of the large {}.",
    "i love my {}!",
    "a close-up photo of the {}.",
    "a photo of my new {}.",
    "a good photo of a {}.",
    "a photo of my dirty {}.",
    "a photo of the nice {}.",
    "a low resolution photo of a {}.",
    "a blurry photo of a {}.",
    "a photo of a nice {}.",
    "a photo of an {}.",
    "a photo of a {}.",
    "This is a photo of a {}.",
]

cars_templates = [
    "a photo of the nice {}.",
    "a photo of the cool {}.",
    "a photo of the clean {}.",
    "a picture of the {}.",
    "a photo of that {}.",
    "a good photo of the {}.",
    "a picture of that {}.",
    "a photo of some {}.",
    "a picture of some {}.",
    "a photo of a cool {}.",
    "a picture of those {}.",
    "itap of my {}.",
    "a picture of a {}.",
    "a photo of the dirty {}.",
    "a photo of those {}.",
    "a photo of the {} thing.",
    "a photo of the {}.",
    "a picture of these {}.",
    "a photo of the hard to see {}.",
    "a photo of the large {}.",
    "a bright photo of a {}.",
]

dtd_templates = [
    "a photo of the {} pattern.",
    "That is a photo of a {}.",
    "a picture of some {}.",
    "a photo of some {}.",
    "a photo of the {} texture.",
    "a photo of your {}.",
    "a photo of the {} thing.",
    "a pixelated photo of the {}.",
    "a photo of many {}.",
    "a photo of the large {}.",
    "a photo of the weird {}.",
    "a cropped photo of the {}.",
    "a photo of an {}.",
    "a photo of that {}.",
    "a photo of a {}.",
    "a picture of an {}.",
    "a photo of a clean {}.",
    "This is a photo of a {}.",
    "a picture of that {}.",
    "a bad photo of a {}.",
    "a photo of a weird {}.",
]


caltech101_templates = [
    "a photo of a weird {}.",
    "a cropped photo of a {}.",
    "a photo of a {}, a type of pet.",
    "a photo of one {}.",
    "a photo of the weird {}.",
    "a rendition of a {}.",
    "a photo of the small {}.",
    "a picture of an {}.",
    "a sketch of a {}.",
    "a photo of the large {}.",
    "a picture of the {}.",
    "a rendering of a {}.",
    "a close-up photo of the {}.",
    "a drawing of a {}.",
    "a photo of some {}.",
    "a picture of a {}.",
    "a good photo of a {}.",
    "a photo of a {}.",
    "This is a photo of a {}.",
    "a photo of an {}.",
    "a photo of the cool {}.",
]

ucf101_templates = [
    "a demonstration of the person {}.",
    "a photo of the person during {}.",
    "a demonstration of the person doing {}.",
    "a demonstration of a person {}.",
    "a demonstration of the person practicing {}.",
    "a demonstration of a person doing {}.",
    "a demonstration of the person during {}.",
    "a video of the person during {}.",
    "a demonstration of a person practicing {}.",
    "a demonstration of a person during {}.",
    "a photo of a person during {}.",
    "a photo of the person doing {}.",
    "a video of a person doing {}.",
    "a example of a person practicing {}.",
    "a example of a person {}.",
    "a video of the person {}.",
    "a video of a person performing {}.",
    "a pixelated photo of the {}.",
    "a video of a person during {}.",
    "a example of the person practicing {}.",
    "a example of a person doing {}.",
]

sun397_templates = [
    "a photo of the nice {}.",
    "a photo of the cool {}.",
    "a photo of many {}.",
    "a photo of a large {}.",
    "a picture of the {}.",
    "a photo of the {}.",
    "a photo of one {}.",
    "a photo of a {}.",
    "a cropped photo of the {}.",
    "a photo of a nice {}.",
    "a photo of a cool {}.",
    "a photo of an {}.",
    "a photo of a weird {}.",
    "a photo of the weird {}.",
    "a picture of those {}.",
    "a photo of a {}, a type of pet.",
    "a photo of the large {}.",
    "a picture of an {}.",
    "That is a photo of a {}.",
    "a photo of some {}.",
    "a low resolution photo of the {}.",
]

eurosat_templates = [
    "a centered satellite photo of the {}.",
    "a painting of a {}.",
    "a centered satellite photo of a {}.",
    "a sculpture of a {}.",
    "a pixelated photo of a {}.",
    "a painting of the {}.",
    "That is a photo of a {}.",
    "a demonstration of the person during {}.",
    "a centered satellite photo of {}.",
    "That is a {} picture.",
    "a rendition of a {}.",
    "a cartoon {}.",
    "That is a {} photo.",
    "a demonstration of a person during {}.",
    "a photo of the hard to see {}.",
    "a photo of the {} pattern.",
    "a origami {}.",
    "a video of the person performing {}.",
    "a demonstration of the person performing {}.",
    "a photo of a {} pattern.",
    "a photo of a hard to see {}.",
]

MINED_TEMPLATES = {
    "oxford_pets": pets_templates,
    "oxford_flowers": flowers_templates,
    "fgvc_aircraft": aircraft_templates,
    "dtd": dtd_templates,
    "eurosat": eurosat_templates,
    "stanford_cars": cars_templates,
    "food101": food_templates,
    "sun397": sun397_templates,
    "caltech101": caltech101_templates,
    "ucf101": ucf101_templates,
    "imagenet": imagenet_templates,
    "imagenet_sketch": imagenet_templates,
    "imagenetv2": imagenet_templates,
    "imagenet_a": imagenet_templates,
    "imagenet_r": imagenet_templates,
}